apiVersion: v1
kind: ResourceQuota
metadata:
  name: vcluster
  namespace: vcluster
spec:
  hard:
    pods: 1000
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-node-critical
          - system-cluster-critical